// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GenerateSlug(arg1:string):Promise<string>;

export function GetAISetting():Promise<domain.AISetting>;

export function SaveAISettingFromFrontend(arg1:domain.AISetting):Promise<void>;
