// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateSlug(arg1) {
  return window['go']['facade']['AIFacade']['GenerateSlug'](arg1);
}

export function GetAISetting() {
  return window['go']['facade']['AIFacade']['GetAISetting']();
}

export function SaveAISettingFromFrontend(arg1) {
  return window['go']['facade']['AIFacade']['SaveAISettingFromFrontend'](arg1);
}
