// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetCdnSetting():Promise<domain.CdnSetting>;

export function SaveCdnSettingFromFrontend(arg1:domain.CdnSetting):Promise<void>;
