// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCdnSetting() {
  return window['go']['facade']['CdnSettingFacade']['GetCdnSetting']();
}

export function SaveCdnSettingFromFrontend(arg1) {
  return window['go']['facade']['CdnSettingFacade']['SaveCdnSettingFromFrontend'](arg1);
}
