// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPwaSetting() {
  return window['go']['facade']['PwaSettingFacade']['GetPwaSetting']();
}

export function HasCustomPwaIcon() {
  return window['go']['facade']['PwaSettingFacade']['HasCustomPwaIcon']();
}

export function RemovePwaIcon() {
  return window['go']['facade']['PwaSettingFacade']['RemovePwaIcon']();
}

export function SavePwaIcon(arg1) {
  return window['go']['facade']['PwaSettingFacade']['SavePwaIcon'](arg1);
}

export function SavePwaSettingFromFrontend(arg1) {
  return window['go']['facade']['PwaSettingFacade']['SavePwaSettingFromFrontend'](arg1);
}
