// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetPwaSetting():Promise<domain.PwaSetting>;

export function HasCustomPwaIcon():Promise<boolean>;

export function RemovePwaIcon():Promise<void>;

export function SavePwaIcon(arg1:string):Promise<void>;

export function SavePwaSettingFromFrontend(arg1:domain.PwaSetting):Promise<void>;
