// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function GetSeoSetting():Promise<domain.SeoSetting>;

export function SaveSeoSettingFromFrontend(arg1:domain.SeoSetting):Promise<void>;
