// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSeoSetting() {
  return window['go']['facade']['SeoSettingFacade']['GetSeoSetting']();
}

export function SaveSeoSettingFromFrontend(arg1) {
  return window['go']['facade']['SeoSettingFacade']['SaveSeoSettingFromFrontend'](arg1);
}
