package repository

import (
	"context"
	"fmt"
	"gridea-pro/backend/internal/domain"
	"os"
	"path/filepath"
	"sync"
)

type linkRepository struct {
	mu     sync.RWMutex
	appDir string
}

func NewLinkRepository(appDir string) domain.LinkRepository {
	return &linkRepository{appDir: appDir}
}

func (r *linkRepository) loadLinks() ([]domain.Link, error) {
	dbPath := filepath.Join(r.appDir, "config", "links.json")
	var db struct {
		Links []domain.Link `json:"links"`
	}

	if err := LoadJSONFile(dbPath, &db); err != nil {
		if os.IsNotExist(err) {
			return []domain.Link{}, nil
		}
		fmt.Printf("Error loading links: %v\n", err)
		return nil, fmt.Errorf("failed to load links from %s: %w", dbPath, err)
	}
	return db.Links, nil
}

func (r *linkRepository) saveLinks(links []domain.Link) error {
	dbPath := filepath.Join(r.appDir, "config", "links.json")
	db := map[string]interface{}{"links": links}
	return SaveJSONFile(dbPath, db)
}

func (r *linkRepository) SaveAll(ctx context.Context, links []domain.Link) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	return r.saveLinks(links)
}

func (r *linkRepository) Create(ctx context.Context, link *domain.Link) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	links, err := r.loadLinks()
	if err != nil {
		return err
	}

	// Check for duplicates if needed, but ID should be unique.
	// Assuming ID is generated by caller or we should check it.
	for _, l := range links {
		if l.ID == link.ID {
			return fmt.Errorf("link ID already exists")
		}
	}

	links = append(links, *link)
	return r.saveLinks(links)
}

func (r *linkRepository) Update(ctx context.Context, id string, link *domain.Link) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	links, err := r.loadLinks()
	if err != nil {
		return err
	}

	found := false
	for i, l := range links {
		if l.ID == id {
			links[i] = *link
			found = true
			break
		}
	}

	if !found {
		return fmt.Errorf("link not found")
	}

	return r.saveLinks(links)
}

func (r *linkRepository) Delete(ctx context.Context, id string) error {
	r.mu.Lock()
	defer r.mu.Unlock()

	links, err := r.loadLinks()
	if err != nil {
		return err
	}

	newLinks := make([]domain.Link, 0, len(links))
	for _, l := range links {
		if l.ID != id {
			newLinks = append(newLinks, l)
		}
	}

	if len(newLinks) == len(links) {
		return fmt.Errorf("link not found")
	}

	return r.saveLinks(newLinks)
}

func (r *linkRepository) GetByID(ctx context.Context, id string) (*domain.Link, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	links, err := r.loadLinks()
	if err != nil {
		return nil, err
	}

	for _, l := range links {
		if l.ID == id {
			return &l, nil
		}
	}
	return nil, fmt.Errorf("link not found")
}

func (r *linkRepository) List(ctx context.Context) ([]domain.Link, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.loadLinks()
}
